---
sensor:
  - platform: adc
    id: temp_analog_reading
    pin: A0
    update_interval: 30s
    internal: true

  - platform: ntc
    sensor: temp_resistance_reading
    name: "${devicenumber}_Cpu_Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    #on_value_range:
    #  above: 90
    #  then: # Security shutdown by overheating
    #    - switch.turn_on: _shutdown

  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
    internal: true