---
sensor:
  - platform: hlw8012
    sel_pin: 12
    cf_pin: 5
    cf1_pin: 13
    current:
      # name: "${devicenumber}_Current"
      id: "Current"
    voltage:
      # name: "${devicenumber}_Voltage"
      id: "Voltage"
    power:
      name: "${devicenumber}_Power"
      accuracy_decimals: 1
      filters:
      - calibrate_linear:
        - 0.0 -> 0.0
        - 67.2 -> 12.0
      - lambda: if (x < 2.0) return 0.0; else return x;
      # - delta: 0.2
    update_interval: 6s
    initial_mode: CURRENT
    # current_resistor: 0.0058